--Tabla Users (uso el plurarl ya que user es una palabra registrada)
CREATE TABLE USERS (
    USER_ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(15) NOT NULL,
    SURNAME VARCHAR(15) NOT NULL,
    GENDER VARCHAR(15) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL UNIQUE,
    USERNAME VARCHAR(15) NOT NULL,
    HASH_PASS VARCHAR(100) NOT NULL,
    PRIMARY KEY (USER_ID)
);

CREATE TABLE CHARACTERS (
    CHARACTER_ID INT NOT NULL AUTO_INCREMENT,
    USER_ID INT NOT NULL,
    NAME VARCHAR(20) NOT NULL,
    BIRTH_PLACE VARCHAR(20) NOT NULL,
    PRONOUNS VARCHAR(10) NOT NULL,
    OCCUPATION VARCHAR(20) NOT NULL,
    RESIDENCE VARCHAR(20) NOT NULL,
    AGE VARCHAR(2) NOT NULL,
    CHARACTERISTICS LONGBLOB NOT NULL,
    SKILLS LONGBLOB NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    PRIMARY KEY (CHARACTER_ID)
);
