version: "3.4"

x-common-variables: &common-variables
  MYSQL_USER: usuario
  MYSQL_PASSWORD: usuario

services:
  mysql-db:
    image: mysql:5.7
    container_name: mysql_container
    environment:
      <<: *common-variables
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 6060:3306
    restart: unless-stopped
    volumes:
      - ./db/sample.sql:/var/lib/mysql
  phpmyadmin:
    depends_on:
      - mysql-db
    image: phpmyadmin/phpmyadmin
    container_name: phpadmin_container
    environment:
      PMA_HOST: mysql-db
    links:
      - mysql-db:mysql-db
    ports:
      - 8080:80
    restart: always
